projects:
  notetaker:
    schemaPath: src/graphql/schema.json
    includes:
      - note
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
